### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by frozenbanana** [Azralii/cinema-booking#1]
Godkänd: Nej
Åtgärd: Det ska vara möjligt för en användare att uppleva en bokning. Just nu får användaren ingen feedback när man klicka på en bokningsknapp. Minsta möjliga åtgärd är att onClick skriv ut ett meddelande till användaren i stil med "You booking has been registered".
---

## Koduppdelning

Jag hade delat upp dina Pages och Komponenter i olika mappar.

Jag hade också haft samma namn på filen som komponenten. T.ex `cinema.jsx` har en Page som heter `Booking`
Byt namn på filen `Booking.jsx`

---

Du fetchar på flera platser men du bör endast göra det i App.js:

```jsx
 // --- App.js
  const [cinemaData, setCinemaData] = useState(null);
  // state to track if application is loading
  const [loading, setLoading] = useState(true);

  // state to track any error message
  const [error, setError] = useState(null);

  // trigger the arrow function inside useEffect ONE time before loading
  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch("db.json");

        if (!response.ok) {
          throw new Error("Network response was not ok");
        }

        const data = await response.json();

        setCinemaData(data.movies);
        localStorage.setItem("movies", JSON.stringify(data.movies));
      } catch (err) {
        setError(err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);
  ...
  
    return (
    <Router>
      <Navbar /> {/* Place it here if it's part of your main layout */}
      <Routes>
        <Route path="/cinema/:id" element={<CinemaDetails  cinemaData={cinemaData}/>} />
        <Route path="/" element={<Cinema  cinemaData={cinemaData} />} />
      </Routes>
    </Router>
  );
```

Kolla på de sista raderna. Vi skickar med cinemaData direkt till dina sidor.

## Git-commits
Du har bara två commits. Det är svårt att se om och hur du har har arbetat de senaste veckorna. Jag vill gärna se att du committar varje arbetstillfälle och dessutom bryter ner ett arbetsområde till en commit. T.ex

"Add route Booking"
"Style CinemaCard"

Och så vidare

## Allmän kodstil
Annars tycker jag du har skrivit fin kod. Fortsätt jobba på!

**Comment by frozenbanana** [comment]
ser bra ut! Du är godkänd!

**Comment by Azralii** [comment]
Tack såmycket Henry
